TaskManagement/SimpleTaskManagement/Areas/HelpPage/Models/HelpPageApiModel.cs
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Net.Http.Headers;
using System.Web.Http.Description;

namespace SimpleTaskManagement.Areas.HelpPage.Models
{
    /// <summary>
    /// The model that represents an API displayed on the help page.
    /// </summary>
    public class HelpPageApiModel
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="HelpPageApiModel"/> class.
        /// </summary>
        public HelpPageApiModel()
        {
            SampleRequests = new Dictionary<MediaTypeHeaderValue, object>();
            SampleResponses = new Dictionary<MediaTypeHeaderValue, object>();
            ErrorMessages = new Collection<string>();
        }

        /// <summary>
        /// Gets or sets the <see cref="ApiDescription"/> that describes the API.
        /// </summary>
        public ApiDescription ApiDescription { get; set; }

        /// <summary>
        /// Gets the sample requests associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleRequests { get; private set; }

        /// <summary>
        /// Gets the sample responses associated with the API.
        /// </summary>
        public IDictionary<MediaTypeHeaderValue, object> SampleResponses { get; private set; }

        /// <summary>
        /// Gets the error messages associated with this model.
        /// </summary>
        public Collection<string> ErrorMessages { get; private set; }
    }
}

TaskManagement/SimpleTaskManagement/Models/ITaskRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SimpleTaskManagement.Models
{
    public interface ITaskRepository
    {
        IEnumerable<Task> GetAll();
        Task Get(int taskID);
        Task Add(Task item);
        void Remove(int taskID);
        bool Update(Task task);
    }
}

TaskManagement/SimpleTaskManagement/Models/Task.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SimpleTaskManagement.Models
{
    public class Task
    {
        public int Id { get; set; }
        public String Description { get; set; }
        public bool IsCompleted { get; set; }
    }
}

TaskManagement/SimpleTaskManagement/Models/TaskRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SimpleTaskManagement.Models
{
    public class TaskRepository : ITaskRepository
    {
        
        public static List<Task> tasks = new List<Task>();
        public TaskRepository()
        {
            //tasks.Add(new Task {Id =1, Description ="Task1", IsCompleted = true });
            //Add(new Task { Id = 2, Description = "Task2", IsCompleted = false });
            //Add(new Task { Id = 3, Description = "Task3", IsCompleted = false });
            //Add(new Task { Id = 4, Description = "Task4", IsCompleted = true });
        }
        //private int _nextId = 1;

        public IEnumerable<Task> GetAll()
        {
            return tasks;
        }

        public Task Get(int taskID)
        {
            return tasks.Find(t => t.Id == taskID);
        }

        public Task Add(Task item)
        {
            if (item == null)
            {
                throw new ArgumentNullException("item");
            }
            item.Id = tasks.Count+1;
            tasks.Add(item);
            return item;
        }

        public void Remove(int taskID)
        {
            tasks.RemoveAll(t => t.Id == taskID);
        }

        public bool Update(Task task)
        {
            if (task == null)
            {
                throw new ArgumentNullException("item");
            }
            Task currenttask = tasks.Find(x => x.Id == task.Id);
            currenttask.IsCompleted = task.IsCompleted;
              
            return true;
        }
    }
}

TaskManagement/SimpleTaskManagement/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using SimpleTaskManagement.Areas.HelpPage.Models;

namespace SimpleTaskManagement.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View("Error");
        }
    }
}

TaskManagement/SimpleTaskManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleTaskManagement.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";

            return View();
        }
    }
}

TaskManagement/SimpleTaskManagement/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SimpleTaskManagement.Controllers
{
    public class TaskController : Controller
    {
        //
        // GET: /Task/
        public ActionResult Index()
        {
            return View();
        }
	}
}

TaskManagement/SimpleTaskManagement/Controllers/TaskManagementController.cs
using SimpleTaskManagement.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SimpleTaskManagement.Controllers
{
    public class TaskManagementController : ApiController
    {
        ITaskRepository repository = new TaskRepository();

        public TaskManagementController()
        {

        }
        public TaskManagementController(ITaskRepository rep)
        {
            repository = rep;
        }
        
        /// <summary>
        /// Gets all the Tasks.
        /// </summary>
        /// <returns>A IEnumerable collection of type Task</returns>
        public IEnumerable<Task> GetAllTasks()
        {
            return repository.GetAll();
        }

        /// <summary>
        /// Saves a Task.
        /// </summary>
        /// <param name="task">Object of type Task which needed to be saved</param>
        /// <returns>The saved Object of type Task with an Id</returns>
        public Task PostTask(Task task)
        {
            task = repository.Add(task);
            return task;
        }

        /// <summary>
        /// Updates the status of the Task either completed or not
        /// </summary>
        /// <param name="taskID">An integer which the Id of the Task to be updated</param>
        /// <param name="task">An object of type Task that is to be updated</param>
        [Route("api/TaskManagement/{taskID:int}")]
        public void PutTask(int taskID, Task task)
        {

            if (!repository.Update(task))
            {
                throw new HttpResponseException(HttpStatusCode.NotFound);
            }
        }

    }
}

TaskManagement/SimpleTaskManagement/Controllers/ValuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace SimpleTaskManagement.Controllers
{
    public class ValuesController : ApiController
    {
        // GET api/values
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/values/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/values
        public void Post([FromBody]string value)
        {
        }

        // PUT api/values/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE api/values/5
        public void Delete(int id)
        {
        }
    }
}

TaskManagement/SimpleTaskManagement/Views/Home/Index.cshtml
<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS, and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>ASP.NET Web API is a framework that makes it easy to build HTTP services that reach
        a broad range of clients, including browsers and mobile devices. ASP.NET Web API
        is an ideal platform for building RESTful applications on the .NET Framework.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301870">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301871">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301872">Learn more &raquo;</a></p>
    </div>
</div>

TaskManagement/SimpleTaskManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>
                    <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
   
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    
</body>
</html>

TaskManagement/SimpleTaskManagement/Views/Task/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src='@Url.Content("~/Scripts/jquery-1.10.2.js")'></script>
</head>
<body>
     <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <h2>Task List</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                <table id="tasksTable">
                    <thead>
                        <tr>
                            <th style="padding-right: 50px;">Task Id</th>
                            <th style="padding-right: 50px;">Task Description</th>
                            <th>Completed</th>
                            <th></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
    <div><input type="button" id="btnAdd" onclick="ShowTaskEntryForm();" value="Add Task" /></div>
    <div id="dvAddTask">
        <table>
            <tr>
                <td>Task Description</td><td><input type="text" id="txtDesc" /></td>
            </tr>
            <tr>
                <td>Is Task Completed</td>
                <td><input type="checkbox" id="chkCompleted" /></td>
            </tr>
            <tr>
                <td></td>
                <td><input type="button" onclick="SaveTask();" id="btnSave" value="Save" /></td>
            </tr>
        </table>

    </div>

    <script type="text/javascript">
        function ShowTaskEntryForm() {
            $("#dvAddTask").css("display", "block");
        }
        function SaveTask()
        {
            $("#dvAddTask").css("display", "none");
            var taskData = {
                "Id": 0,
                "Description": $("#txtDesc").val(),
                "isCompleted": $("#chkCompleted").is(':checked')

            };
            $.ajax({
                type: "post",
                url: "http://localhost:10320/api/TaskManagement/" ,
                data: JSON.stringify(taskData),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    var checkedString = "";
                    if (data.IsCompleted)
                        checkedString = "checked='checked'";
                    $("#tasksTable tbody").append(
                 "<tr class='table'>" +
                   "<td>" + data.Id + "</td>" +
                   "<td>" + data.Description + "</td>" +
                   "<td><input type='checkbox'" + checkedString + " /></td>" +
                   "<td>" + '<input type="button" class="btnCls" id="btnEdit" onclick="EditTask(this,' + data.Id + ')" value="Save Status"  />' +
             "</td>" +
           "</tr>");

                    $("#txtDesc").val("");
                },
                error: function (xhr) {
                    alert(xhr.responseText);
                }
            });

        }
        $(document).ready(function () {
            $("#dvAddTask").css("display", "none");
            GetAllTasks();
        });

        function EditTask(trObject,taskId)
        {
            var isCompleted = $(trObject).closest("tr").find("input[type='checkbox']").is(':checked');
            var taskData = {
                "Id": taskId,
                "Description":"",
                "isCompleted": isCompleted
                
            };
            $.ajax({
                type: "put",
                url: "http://localhost:10320/api/TaskManagement/" + taskId,
                data: JSON.stringify(taskData),
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data, status, jqXHR) {
                },
                error: function (xhr) {
                    alert(xhr.responseText);
                }
            });
            
        }


        





      function GetAllTasks()
      {
          //debugger;
          jQuery.support.cors = true;
          $.ajax({
              url: 'http://localhost:10320/api/TaskManagement',
              type: 'GET',
              dataType: 'json',
              success: function (data) {
                  debugger;
                  if ($("#tasksTable tbody").length == 0) {
                      $("#tasksTable").append("<tbody></tbody>");
                  }
                  $.each(data, function (index, task) {
                      var checkedString = "";
                      if (task.IsCompleted)
                          checkedString = "checked='checked'";
                      $("#tasksTable tbody").append(
                 "<tr class='table'>" +
                   "<td>" + task.Id + "</td>" +
                   "<td>" + task.Description + "</td>" +
                   "<td><input type='checkbox'" + checkedString + " /></td>" +
                   "<td>" +'<input type="button" class="btnCls" id="btnEdit" onclick="EditTask(this,'+task.Id+')" value="Save Status"  />' +
             "</td>" +
           "</tr>");

                  })
              },
              error: function () {
                 
              }
          });

          


      }
  
    </script>
    @Scripts.Render("~/bundles/bootstrap")
</body>
</html>